### PR TITLE
Update EnderiteOre.java

### PR DESCRIPTION
**Pull request by ImpulsiveLad**
Changed the hardness of enderite ore from 9 to 30 (same as ancient debris as opposed to same as end_stone)

### CODE REVIEW

**Comment by ImpulsiveLad** [comment]
@Nic4Las Sorry if you're busy and I'm bothering you but could you review this and accept if its all good? The lack of hardness difference between enderite ore and end stone is breaking part of my modpack

**Comment by Nic4Las** [comment]
Yeah sorry uni is a bit much at the moment. I will have a look when I'm home today and will let you know.

**Comment by ImpulsiveLad** [comment]
Thank you, I get ya I'm in an engineering major too

**Comment by Nic4Las** [comment]
Okay, I just checked. With a resistance value of 30 nothing in the game can crack the ore. Other mods might have an explosive that is strong enough to break it with that level of resistance, but I can't change the default value, because otherwise, nothing would be able to crack it.

**Comment by ImpulsiveLad** [comment]
......But you don't need to mine it???? Its indestructible like bedrock. You use tnt to make it become cracked, also ancient debris has a resistance value of 30.
These are the highest hardness values in vanilla:
Screenshot 2023-10-24 121627

 https://minecraft.fandom.com/wiki/Breaking
 
 Unless I changed the wrong number, 30 should be a very reasonable hardness rather than the default of the mod which is the same as end stone

**Comment by Nic4Las** [comment]
The value you changed in the pull request is called resistance in the yarn mappings. It dictates the resistance of a block to explosions. There are two different blocks of enderite ore in the mod. The normal Enderite ore is impossible to mine but can be blown up relatively easily and the cracked enderite ore that can be mined using anything better than a diamond pickaxe but not be blown up. With a resistance value of 30 nothing in the vanilla game can blow up the normal ore and crack it. This is a problem because only the cracked ore is minable. So If I changed the resistance value of the normal ore enderite would become unobtainable in survival.

What are you trying to do? Why would the resistance of the uncracked ore be important?

Also the link you send deals with the hardness of a block. The hardness dictates the mining speed of the block. Here is the wiki entry for resistance (deals with explosions) https://minecraft.wiki/w/Explosion#Blast_resistance. As you can see there is nothing in the game with a higher resistance than 9 that can be blown up in the vanilla game.

**Comment by ImpulsiveLad** [comment]
Hmmmmmmm, I see, ancient debris has a resistance of 1200, but tnt cannot break blocks with a resistanance of 10 or above?

**Comment by ImpulsiveLad** [comment]
I read the code closer, I see that explosions are MEANT to break the ore, it will then just become cracked

I wonder why the literaly NUKE in the other mod doesn't count as an explosion. I can verify creepers can crack the ore in addition to tnt so the code on your end isn't strictly for minecraft:tnt

**Comment by ImpulsiveLad** [comment]
https://streamable.com/rciwr5
As you can see, tnt and creepers work, the nuke doesn't. I don't know who coded the nuke but I'm guessing its not a "explosion"

**Pull request closed without merging**
